from game.piece import *
class Board:
    def __init__(self):
        self.grid = [[None for _ in range(8)] for _ in range(8)]

    def set(self, row, col, piece):
        self.grid[row][col] = piece

    def setup(self):
        pawn_1 = Pawn("pieces/pawn.png", "pawn", "white")
        pawn_2 = Pawn("pieces/pawn.png", "pawn", "white")
        pawn_3 = Pawn("pieces/pawn.png", "pawn", "white")
        pawn_4 = Pawn("pieces/pawn.png", "pawn", "white")
        pawn_5 = Pawn("pieces/pawn.png", "pawn", "white")
        pawn_6 = Pawn("pieces/pawn.png", "pawn", "white")
        pawn_7 = Pawn("pieces/pawn.png", "pawn", "white")
        pawn_8 = Pawn("pieces/pawn.png", "pawn", "white")
        rook = Rook("pieces/rook.png", "rook", "white")
        knight = Knight("pieces/knight.png", "knight", "white")
        bishop = Bishop("pieces/bishop.png", "bishop", "white")
        queen = Queen("pieces/queen.png", "queen", "white")
        king = King("pieces/king.png", "king", "white")

        self.set(0,0, rook)
        self.set(0,1, knight)
        self.set(0,2, bishop)
        self.set(0,3, king)
        self.set(0,4, queen)
        self.set(0,5, bishop)
        self.set(0,6, knight)
        self.set(0,7, rook)
        self.set(1,0, pawn_1)
        self.set(1,1, pawn_2)
        self.set(1,2, pawn_3)
        self.set(1,3, pawn_4)
        self.set(1,4, pawn_5)
        self.set(1,5, pawn_6)
        self.set(1,6, pawn_7)
        self.set(1,7, pawn_8)

        black_pawn_1 = Pawn("pieces/black/pawn.png", "pawn", "black")
        black_pawn_2 = Pawn("pieces/black/pawn.png", "pawn", "black")
        black_pawn_3 = Pawn("pieces/black/pawn.png", "pawn", "black")
        black_pawn_4 = Pawn("pieces/black/pawn.png", "pawn", "black")
        black_pawn_5 = Pawn("pieces/black/pawn.png", "pawn", "black")
        black_pawn_6 = Pawn("pieces/black/pawn.png", "pawn", "black")
        black_pawn_7 = Pawn("pieces/black/pawn.png", "pawn", "black")
        black_pawn_8 = Pawn("pieces/black/pawn.png", "pawn", "black")
        black_rook = Rook("pieces/black/rook.png", "rook", "black")
        black_knight = Knight("pieces/black/knight.png", "knight", "black")
        black_bishop = Bishop("pieces/black/bishop.png", "bishop", "black")
        black_queen = Queen("pieces/black/queen.png", "queen", "black")
        black_king = King("pieces/black/king.png", "king", "black")

        self.set(7,0, black_rook)
        self.set(7,1, black_knight)
        self.set(7,2, black_bishop)
        self.set(7,3, black_king)
        self.set(7,4, black_queen)
        self.set(7,5, black_bishop)
        self.set(7,6, black_knight)
        self.set(7,7, black_rook)
        self.set(6,0, black_pawn_1)
        self.set(6,1, black_pawn_2)
        self.set(6,2, black_pawn_3)
        self.set(6,3, black_pawn_4)
        self.set(6,4, black_pawn_5)
        self.set(6,5, black_pawn_6)
        self.set(6,6, black_pawn_7)
        self.set(6,7, black_pawn_8)